# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

coverTreeNeighbor <- function(dataset, k) {
    .Call('RcppMLPACK_coverTreeNeighbor', PACKAGE = 'RcppMLPACK', dataset, k)
}

kmeans <- function(data, clusters) {
    .Call('RcppMLPACK_kmeans', PACKAGE = 'RcppMLPACK', data, clusters)
}

